name: test
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        ruby: ["3.0", "3.1", "3.2"]
        gemfile: [Gemfile]
        include:
          - ruby: "3.2"
            gemfile: "gemfiles/rails-7.0.gemfile"
          - ruby: "3.2"
            gemfile: "gemfiles/rails-6.1.gemfile"

    env:
      BUNDLE_GEMFILE: "${{ matrix.gemfile }}"

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rake
    - name: Send coverage
      uses: paambaati/codeclimate-action@v5
      env:
        CC_TEST_REPORTER_ID: 921d046db793707b7d0c0d1305970a137fdf98fbc6ceeb6c355c44757040244f
